### Data Pre-processing || ML Lab Task- 01

  Done by: **Sorowar Mahabub**, C201032.

Dataset Credit: Kaggle

In [1]:
# NumPy, a module for Python, makes sure that the precompiled mathematical and numerical functions and functionalities of Numpy guarantee great execution speed.
import numpy as np

# Pandas, a Python Library, provides high-performance data manipulation and analysis tool using its powerful data structures.
import pandas as pd

# OS module allows to interface with the underlying operating system
import os

In [4]:

# ......................................................................
# If the dataset is in the Google Drive, You Can write the following:
#Connecting/ Mounting with Google Drive
from google.colab import drive
drive.mount('/content/drive/')

#Assigning/ Defining the Root's Path
root_path= '/content/drive/MyDrive/Colab Notebooks/ML Lab/Task_01/ml_lab_task_01_data_C201032.csv'

dataset = pd.read_csv(root_path)
print('Our the datasets......')
# ......................................................................

# Print the shape of the dataset
print ('dataset: %s'%(str(dataset.shape)))

# This is formatted as code --- to check your CODE

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).
Our the datasets......
dataset: (15, 4)

In [5]:
# print the dataset
dataset

      Country   Age   Salary Purchased
0       India  34.0  92000.0       Yes
1   Sri lanka  22.0  25000.0       Yes
2       China  31.0  74000.0       Yes
3   Sri lanka  29.0      NaN        No
4       China  55.0  98000.0       Yes
5       India  24.0  30000.0        No
6   Sri lanka  28.0  40000.0        No
7       India   NaN  60000.0        No
8       China  51.0  89000.0       Yes
9       India  44.0  78000.0       Yes
10  Sri lanka  21.0  20000.0        No
11      China  25.0  30000.0       Yes
12      India  33.0  45000.0       Yes
13      India  42.0  65000.0       Yes
14  Sri lanka  33.0  22000.0        No

In [10]:
# Separate the dependent and independent variables

# Independent variable: selects all rows and all columns except the last one from the dataset.
X = dataset.iloc[:,:-1].values

# Dependent variable: selects all rows and only the fourth column (index 3) from the dataset
Y = dataset.iloc[:,3].values

In [11]:
# Print the X and Y
print ('X: %s'%(str(X)))

print ('-----------------------------------')

print ('Y: %s'%(str(Y)))

X: [['India' 34.0 92000.0]
 ['Sri lanka' 22.0 25000.0]
 ['China' 31.0 74000.0]
 ['Sri lanka' 29.0 nan]
 ['China' 55.0 98000.0]
 ['India' 24.0 30000.0]
 ['Sri lanka' 28.0 40000.0]
 ['India' nan 60000.0]
 ['China' 51.0 89000.0]
 ['India' 44.0 78000.0]
 ['Sri lanka' 21.0 20000.0]
 ['China' 25.0 30000.0]
 ['India' 33.0 45000.0]
 ['India' 42.0 65000.0]
 ['Sri lanka' 33.0 22000.0]]
-----------------------------------
Y: ['Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes'
 'Yes' 'No']

In [18]:
!pip install scikit-learn
from sklearn.impute import SimpleImputer
import pandas as pd

df = pd.DataFrame(X)
df.head()
df.fillna(0, inplace=True)

# Replace missing values with the mean of each column
df.fillna(df.mean(), inplace=True)

# Replace missing values with the median of each column
df.fillna(df.median(), inplace=True)

# Replace missing values with the mode of each column
df.fillna(df.mode().iloc[0], inplace=True)

imputer = SimpleImputer(missing_values=0, strategy='mean')
imputer.fit(df.iloc[:, 1:3])

df.iloc[:, 1:3] = imputer.transform(df.iloc[:, 1:3])

df.head()

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.23.5)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.2.0)

<ipython-input-18-c4e13397dfd1>:10: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.mean(), inplace=True)
<ipython-input-18-c4e13397dfd1>:13: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.median(), inplace=True)

           0     1             2
0      India  34.0  92000.000000
1  Sri lanka  22.0  25000.000000
2      China  31.0  74000.000000
3  Sri lanka  29.0  54857.142857
4      China  55.0  98000.000000

In [20]:
# # Scikit-learn provides a range of supervised and unsupervised learning algorithms via a consistent interface in Python.
# # And The sklearn.preprocessing package provides several common utility functions and transformer classes
# from sklearn.impute import SimpleImputer

# imputer = SimpleImputer(missing_values = 'NaN',strategy = 'mean')
# # Parameters are-
# # missing_values : The missing values in our dataset are called as NaN (Not a number).Default is NaN
# # strategy       : replace the missing values by mean/median/mode. Default is mean.
# # axis           : if axis = 0, we take we of the column and if axis = 1, we take mean value of row.)


# # Fit imputer for columns 1 and 2 of X matrix.
# imputer = imputer.fit(X[:,1:3]) # Note: Index starts with 0. Upper bound (3) is not included.

# #Replace missing data with mean of column
# X[:,1:3] = imputer.transform(X[:,1:3])

In [19]:
print ('X: %s'%(str(X)))

X: [['India' 34.0 92000.0]
 ['Sri lanka' 22.0 25000.0]
 ['China' 31.0 74000.0]
 ['Sri lanka' 29.0 0]
 ['China' 55.0 98000.0]
 ['India' 24.0 30000.0]
 ['Sri lanka' 28.0 40000.0]
 ['India' 0 60000.0]
 ['China' 51.0 89000.0]
 ['India' 44.0 78000.0]
 ['Sri lanka' 21.0 20000.0]
 ['China' 25.0 30000.0]
 ['India' 33.0 45000.0]
 ['India' 42.0 65000.0]
 ['Sri lanka' 33.0 22000.0]]

In [21]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

labelencoder_X = LabelEncoder()
X[:,0] = labelencoder_X.fit_transform(X[:,0])
X[:,0]

array([1, 2, 0, 2, 0, 1, 2, 1, 0, 1, 2, 0, 1, 1, 2], dtype=object)

#### Dummy Encoding

    * The above encoding will result in a problem.
    * The label encoding transforms the data as shown in the table above.
    * The Machine learning algorithm will assume that China>India>Sri Lanka.
    * But this is not the case. We just converted the categorical value and assigned it to a numeric value.
    * Hence there is a need to apply Dummy encoding to the above dataset.

| Country | China | India | Sri Lanka |
|:--------|:------|:------|:----------|
| China   |   1   |  0    |    0      |   
| India   |   0   |  1    |    0      |   
| Srilanka|   0   |  0    |    1      |   
| India   |   0   |  1    |    0      |  
| Srilanka|   0   |  0    |    1      |  
| China   |   1   |  0    |    0      |

In [23]:
# Display the first five rows of the X array
!head -5 X

# Print the number of columns in the X array
!echo "Number of columns in X:"
!echo $(head -1 X | wc -w)

# Import the OneHotEncoder class from sklearn.preprocessing
from sklearn.preprocessing import OneHotEncoder

# Instantiate the OneHotEncoder object with the correct parameter
ohe = OneHotEncoder(sparse=False)

# Fit and transform the X array using the OneHotEncoder object
X_transformed = ohe.fit_transform(X)

# Print the shape of the transformed X array
!echo "Shape of transformed X:"
!echo $(echo $X_transformed | wc -w)

head: cannot open 'X' for reading: No such file or directory
Number of columns in X:
head: cannot open 'X' for reading: No such file or directory
0
Shape of transformed X:

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

/bin/bash: line 31: 0.: command not found
/bin/bash: line 32: [0.: command not found
/bin/bash: line 33: 0.: command not found
/bin/bash: line 34: [1.: command not found
/bin/bash: line 35: 0.: command not found
/bin/bash: line 36: [0.: command not found
/bin/bash: line 37: 0.: command not found
/bin/bash: line 38: [1.: command not found
/bin/bash: line 39: 0.: command not found
/bin/bash: line 40: [0.: command not found
/bin/bash: line 41: 0.: command not found
/bin/bash: line 42: [0.: command not found
/bin/bash: line 43: 0.: command not found
/bin/bash: line 44: [0.: command not found
/bin/bash: line 45: 1.: command not found
/bin/bash: line 46: [1.: command not found
/bin/bash: line 47: 0.: command not found
/bin/bash: line 48: [0.: command not found
/bin/bash: line 49: 0.: command not found
/bin/bash: line 50: [0.: command not found
/bin/bash: line 51: 0.: command not found
/bin/bash: line 52: [1.: command not found
/bin/bash: line 53: 0.: command not found
/bin/bash: line 54: [0.: command not found
/bin/bash: line 55: 0.: command not found
/bin/bash: line 56: [0.: command not found
/bin/bash: line 57: 0.: command not found
/bin/bash: line 58: [0.: command not found
/bin/bash: line 59: 0.: command not found
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

In [28]:
# # Applying the OneHotEncoder to the first column[0]
# onhotencoder = OneHotEncoder(categorical_features = [0])
# X=onhotencoder.fit_transform(X).toarray()

In [24]:
# Encoding the categorical data for Y matrix
labelencoder_Y = LabelEncoder()
Y = labelencoder_X.fit_transform(Y)
Y

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0])

In [26]:
###############################################################
#       Step 5 : Splitting the dataset                        #
###############################################################

from sklearn.model_selection import train_test_split

# The test size is taken as 20% of the total dataset i.e., out of 15 only 3 rows are taken as test set
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,random_state = 0)

In [27]:
# Print the shape of the dataset
print ('X_train: %s'%(str(X_train.shape)))
print ('----------------')
print ('X_test: %s'%(str(X_test.shape)))
print ('----------------')
print ('Y_train: %s'%(str(Y_train.shape)))
print ('----------------')
print ('Y_test: %s'%(str(Y_test.shape)))
print ('----------------')

X_train: (12, 3)
----------------
X_test: (3, 3)
----------------
Y_train: (12,)
----------------
Y_test: (3,)
----------------

#### 3. Scale Our Features
    *  Most of the times, the dataset will contain features highly varying in magnitudes, units and range.
    *  Since the machine learning algorithms use Eucledian distance between two data points in their computations, this is
       result in wrong prediction.
      
We need to put the variables in same range, in the same scale so that no variable dominates the other variable.

In [29]:
###############################################################
#       Step 6 : Feature Scaling                              #
###############################################################

from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()

# We need to fit and transform the training set
X_train = sc_X.fit_transform(X_train)

# We need to fit the test set
X_test = sc_X.transform(X_test)

In [30]:
X_train

array([[ 0.        ,  1.0051925 ,  0.89670288],
       [ 1.41421356,  0.1600625 , -0.97467705],
       [-1.41421356,  1.85032251,  1.56505286],
       [-1.41421356,  0.0064025 ,  0.76303289],
       [ 0.        ,  0.8515325 ,  0.4622754 ],
       [ 1.41421356, -0.7618975 , -1.04151205],
       [ 0.        , -2.37532751,  0.29518791],
       [-1.41421356, -0.4545775 , -0.70733706],
       [ 1.41421356, -0.1472575 , -1.70986202],
       [ 0.        ,  0.2368925 ,  1.36454787],
       [ 0.        , -0.5314075 , -0.70733706],
       [ 0.        ,  0.1600625 , -0.20607458]])

In [31]:
X_test

array([[ 1.41421356, -0.6850675 , -0.87442455],
       [ 1.41421356, -0.2240875 , -0.37316207],
       [-1.41421356,  1.54300251,  1.26429537]])

Now the all the data are in same scale. We can now apply different Machine learning model to the dataset.